server:
  port: 9010
spring:  application:    name: organization  jpa:    hibernate:      ddl-auto: update
    show-sql: true    datasource:    username: root
    password: Cloud@123$
    url: jdbc:mysql://localhost:3306/fisglobal-org
    driver-class-name: com.mysql.cj.jdbc.Driver